const data = [
  {
    id: 1,
    titulo: "Sobrevivendo no inferno",
    autor: "Racionais Mc’s",
    pages: 452,
    categoria: "Literatura",
    recomenda: false,
    leu: false,
  },
  {
    id: 2,
    titulo: "A teus pés",
    autor: "Ana Cristina Cesar",
    pages: 520,
    categoria: "Psicologia",
    recomenda: false,
    leu: false,
  },
  {
    id: 3,
    titulo: "O seminário dos ratos",
    autor: "Lygia Fagundes Teles",
    pages: 638,
    categoria: "Literatura",
    recomenda: false,
    leu: false,
  },
  {
    id: 4,
    titulo: "O espelho",
    autor: "Machado de Assis",
    pages: 255,
    categoria: "Literatura",
    recomenda: false,
    leu: false,
  },
  {
    id: 5,
    titulo: "O marinheiro",
    autor: "Fernando Pessoa",
    pages: 865,
    categoria: "Literatura",
    recomenda: false,
    leu: false,
  },
  {
    id: 6,
    titulo: "A falência",
    autor: "Júlia Lopes de Almeida,",
    pages: 611,
    categoria: "Psicologia",
    recomenda: false,
    leu: false,
  },
  {
    id: 7,
    titulo: "O Ateneu",
    autor: "Raul Pompéia ",
    pages: 321,
    categoria: "Literatura",
    recomenda: false,
    leu: false,
  },
  {
    id: 8,
    titulo: "História do Cerco de Lisboa",
    autor: "José Saramago",
    pages: 456,
    categoria: "Historia",
    recomenda: false,
    leu: false,
  },
  {
    id: 9,
    titulo: "Quarto de despejo",
    autor: "Carolina Maria de Jesus",
    pages: 789,
    categoria: "Psicologia",
    recomenda: false,
    leu: false,
  },
  {
    id: 10,
    titulo: "A cabra vadia",
    autor: "Nelson Rodrigues",
    pages: 999,
    categoria: "Historia",
    recomenda: false,
    leu: false,
  },
  {
    id: 11,
    titulo: "A Relíquia",
    autor: "Eça de Queirós",
    pages: 365,
    categoria: "Historia",
    recomenda: false,
    leu: false,
  },
  {
    id: 12,
    titulo: "Angústia",
    autor: "Graciliano Ramos",
    pages: 206,
    categoria: "Literatura",
    recomenda: false,
    leu: false,
  },
  {
    id: 13,
    titulo: "Campo Geral",
    autor: "João Guimarães Rosa",
    pages: 511,
    categoria: "Literatura",
    recomenda: false,
    leu: false,
  },
  {
    id: 14,
    titulo: "Memórias de um sargente de milícias",
    autor: "Manuel Antônio de Almeida",
    pages: 116,
    categoria: "Psicologia",
    recomenda: false,
    leu: false,
  },
];

module.exports = data;